Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "ubuntu/bionic64"  
  end

config.vm.define "node1" do |subconfig|
  subconfig.vm.box = "ubuntu/bionic64"  
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  sudo wget https://www.atlassian.com/software/confluence/      downloads/binary/atlassian-confluence-7.3.1-x64.bin
  sudo chmod a+x atlassian-confluence-7.3.1-x64.bin
  sudo ./atlassian-confluence-7.3.1-x64.bin
  SHELL
  config.vm.network "forwarded_port", guest: 80, host: 8080
end

config.vm.define 'node2' do |subconfig|
  subconfig.vm.box = 'centos/7'
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  # Setting MySQL root user password root/root
  debconf-set-selections <<< 'mysql-server mysql-server/root_password password 123456'
  debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password 123456'
  # Installing packages
  apt-get install -y mysql-server mysql-client
  # Allow External Connections on your MySQL Service
  sudo sed -i -e 's/bind-addres/#bind-address/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  sudo sed -i -e 's/skip-external-locking/#skip-external-locking/g' /etc/mysql/mysql.conf.d/mysqld.cnf
  mysql -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123456'; FLUSH privileges;"
  sudo service mysql restart
  # create client database
  mysql -u root -proot -e "CREATE DATABASE CONFLUENCE;"
  SHELL
  config.vm.network 'forwarded_port', guest: 3306, host: 3306
end

end




